apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns-pihole
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: external-dns-pihole-readonly-ingress
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
rules:
- apiGroups:
  - extensions
  resources: ["*"]
  verbs:
  - get
  - list
  - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: external-dns-pihole-role-binding
subjects:
- kind: ServiceAccount
  name: external-dns-pihole
  namespace: default
roleRef:
  kind: ClusterRole
  name: external-dns-pihole-readonly-ingress
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns-pihole
  labels:
    app: external-dns-pihole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: external-dns-pihole
  template:
    metadata:
      labels:
        app: external-dns-pihole
    spec:
      serviceAccountName: external-dns-pihole
      containers:
      - name: external-dns-pihole
        image: pobek/external-dns-pihole:v0.1
        env:
          - name: DOMAIN_NAME
            value: local.lan
          - name: PIHOLE_DNS
            value: pi.hole:9090
          - name: MODE
            value: PROD